### ISSUE TITLE
kitchen test fail: create jira posturesql db user run into SyntaxError

### ISSUE THREAD

**Issue by DennyZhang** [juliandunn/jira#3]
Here is the chef update output, triggered by "kitchen converge default-centos-65".

         * package[make] action nothing (skipped due to action :nothing)
        (skipped due to action :nothing)
         * package[patch] action nothing (skipped due to action :nothing)
       Recipe: postgresql::ruby
        (up to date)
       Recipe: jira::local_database
       
       ================================================================================
       Error executing action `create` on resource 'postgresql_database_user[jira]'
       ================================================================================
       
       PG::SyntaxError
       ---------------
       ERROR:  syntax error at or near "NOREPLICATION"
       LINE 1: ...bY1EppLZP6GI5Q0Z3U' NOCREATEDB NOCREATEROLE LOGIN NOREPLICAT...
                                                             ^
       
       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_postgresql_user.rb:53:in `exec'
       /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_postgresql_user.rb:53:in `action_create'
       
       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/jira/recipes/local_database.rb
       
        32: postgresql_database_user 'jira' do
        33:   connection postgresql_connection_info
        34:   password node['jira']['local_database']['password']
        35:   action :create
        36: end
        37: 
       
       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/jira/recipes/local_database.rb:32:in `from_file'
       
       postgresql_database_user("jira") do
         provider Chef::Provider::Database::PostgresqlUser
         action [:create]
         retries 0
         retry_delay 2
         guard_interpreter :default
         username "jira"
         host "localhost"
         privileges [:all]
         login true
         cookbook_name "jira"
         recipe_name "local_database"
         connection {:host=>"localhost", :username=>"postgres", :password=>"IHP9aWAclXGuxMV3mXV8"}
         password "qdbY1EppLZP6GI5Q0Z3U"
       end
       
       Recipe: jira::server
       
           - restart service service[jira]
       Recipe: postgresql::server_redhat
       
           - restart service service[postgresql]
       
       Running handlers:
       [2015-02-18T17:09:14+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-02-18T17:09:14+00:00] ERROR: Exception handlers complete
       [2015-02-18T17:09:14+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 41 resources updated in 1112.680769212 seconds
       [2015-02-18T17:09:15+00:00] ERROR: postgresql_database_user[jira] (jira::local_database line 32) had an error: PG::SyntaxError: ERROR:  syntax error at or near "NOREPLICATION"
       LINE 1: ...bY1EppLZP6GI5Q0Z3U' NOCREATEDB NOCREATEROLE LOGIN NOREPLICAT...
                                                             ^
       
       [2015-02-18T17:09:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    Converge failed on instance <default-centos-65>.
    Please see .kitchen/logs/default-centos-65.log for more details
    ------Exception-------
      Class: Kitchen::ActionFailed
      Message: SSH exited (1) for command: [sh -c '
     sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json

**Comment by juliandunn** [comment]
I can't reproduce this at all. Here's my kitchen run: https://gist.github.com/juliandunn/cc0d677b2cd749845816

**Comment by juliandunn** [comment]
never mind... I found the problem. It is with the database cookbook, so I filed a bug over there. https://github.com/opscode-cookbooks/database/issues/136

**Comment by DennyZhang** [comment]
@juliandunn thanks a lot.

I just did another kitchen+vagrant test, the problem remains.

**Comment by juliandunn** [comment]
@DennyZhang make sure you remove your Berksfile.lock before doing so.

**Comment by DennyZhang** [comment]
@juliandunn Yes, remove Berksfile.lock and try it again. It works now.

Thanks!
