### ISSUE TITLE
Problem with Jira account

### ISSUE THREAD

**Issue by Dreeg** [juliandunn/jira#4]
Hi,
I'm testing this cookbook in kitchen and I have a problem with jira user that can't do anything.
First kitchen converge return this error:

           Error executing action `restart` on resource 'service[jira]'

            Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service jira restart ----
           STDOUT: Stopping jira
           jira stopped successfully
           Starting jira
           STDERR: 
           ---- End output of /sbin/service jira restart ----
           Ran /sbin/service jira restart returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/jira/recipes/server.rb
           
           100: service 'jira' do
           101:   supports :restart => true
           102:   action [:enable, :start]
           103: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jira/recipes/server.rb:100:in `from_file'
           
           service("jira") do
             action [:enable, :start]
             updated true
             supports {:restart=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "jira"
             enabled true
             running true
             pattern "jira"
             declared_type :service
             cookbook_name "jira"
             recipe_name "server"
           end

I can resolve this in ssh connection and launching, by root user, "passwd -u jira -f".

I don't understand why jira account goind in lock mode.
After this operation, if I re-launch a kitchen converge, chef return a start (not restart) error:

           Error executing action `start` on resource 'service[jira]'

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service jira start ----
           STDOUT: Starting jira
           STDERR: 
           ---- End output of /sbin/service jira start ----
           Ran /sbin/service jira start returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/jira/recipes/server.rb
           
           100: service 'jira' do
           101:   supports :restart => true
           102:   action [:enable, :start]
           103: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jira/recipes/server.rb:100:in `from_file'
           
           service("jira") do
             action [:enable, :start]
             supports {:restart=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "jira"
             enabled true
             pattern "jira"
             declared_type :service
             cookbook_name "jira"
             recipe_name "server"
           end

Centos 6.5
Chef-Client 12.3.0
Jira Cookbook 1.0.2

**Comment by Dreeg** [comment]
A workaround is change user creation method
# user 'jira' do
#   comment 'Atlassian JIRA'
#   home node['jira']['homedir']
#   system true
#   action :create
# end

with

execute 'user' do
  command "useradd jira -d #{node['jira']['homedir']}"
  action :run
end

But this method is just a workaround..


Does anyone have a solution to comply with the chef rules, using resource?

**Comment by juliandunn** [comment]
I don't think it has anything to do with the account being in a locked state when first created. That is normal; a locked account can still be used to run processes when they are initiated by root.

My experience is that the startup script (which I got off Atlassian's Wiki) is notoriously unreliable because Jira is often not a well-behaved Java process.

**Comment by Dreeg** [comment]
Hi @juliandunn,
thanks for the reply.
Any suggestions to leave me?

For the ability to run services with users blocked, I tried with
```
su jira
jira $: /sbin/service jira restart
```
but asks me for a password (clearly non-existent, also confirmed by the /etc/shadow) and I do not do anything (stop/start/restart)..

**Comment by juliandunn** [comment]
@Dreeg you can always `sudo /sbin/service jira [action]` that way you do not need to use the jira account.

Also feel free to complain at Atlassian about their init script :grin:
